project_id = "yhewlncfxsorfzcoryxd"

[functions.list-users]
verify_jwt = false

[functions.list-withdrawals]
verify_jwt = false

[functions.grant-weekly-bonus]
verify_jwt = false

[functions.create-support-ticket]
verify_jwt = false

[functions.list-support-tickets]
verify_jwt = false

[functions.delete-support-ticket]
verify_jwt = false
