project_id = "yhewlncfxsorfzcoryxd"

[functions.list-users]
verify_jwt = false

[functions.list-withdrawals]
verify_jwt = false

[functions.grant-weekly-bonus]
verify_jwt = false

[functions.create-support-ticket]
verify_jwt = false

[functions.list-support-tickets]
verify_jwt = false

[functions.delete-support-ticket]
verify_jwt = false

[functions.update-withdrawal-status]
verify_jwt = false

[functions.buss-webhook]
verify_jwt = false

[functions.process-deposit]
verify_jwt = false

[functions.reprocess-confirmed-deposits]
verify_jwt = false

[functions.admin-credit-deposits]
verify_jwt = false
