// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhewlncfxsorfzcoryxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZXdsbmNmeHNvcmZ6Y29yeXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTgwNzEsImV4cCI6MjA3MTE5NDA3MX0.hLd6dkw6Q6l9CWTcXQT0poBXPWHGA0ozYd-avjKiehE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});